### ISSUE TITLE
Analytics app - liquidity depth shows the wrong numbers

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#109]
ETH/BNT liquidity is shown as x2 the actual liquidity.
Every other pool is shown as 1/2 of the actual liquidity.
We should show the actual locked value in each pool.

**Comment by Velua** [comment]
>  We should show the actual locked value in each pool.

What's the locked value? @yudilevi

**Comment by Velua** [comment]
@yudilevi sent you the preview link in Telegram.

**Comment by yudilevi** [comment]
Yup, looks great! But let's discuss the method, interested to hear how it works in terms of performance.

**Comment by Velua** [comment]
Reserve balances for every pool is queried, using the eth-multicall this isn't too expensive, requests sent to the contract are being chunked in sizes.... ```[600,100,50,10]``` so most requests get away with a max size of 600 but should it fail it will go to 100, should that fail then 50... etc, 

I've made the drop from 600 to 100 pretty big because each time it will fail and goes down a level, the more water falling it creates, making the user wait longer for the requests to come through. 

When we have the reserve balances, we just work out which one is BNT, use Binance to determine the value of the BNT token, then work out the USD value of the all the BNT, then assume the same USD value on the other end of V1 converters with a 50 50 CW. 

The liquidity depth is recorded per **reserve** not **pool** behind the scenes, then it's calculated per pool in a reactive Vue getter before given to the view layer, doing it this way lets us easily calculate the liquidity depth per token as well. 

We used to pull liquidity depth from the Bancor API if the API supported a pool but we're now just using it for volume metrics instead.
