### ISSUE TITLE
Remove liquidity - wrong output amount

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#118]
From a user:

![image](https://user-images.githubusercontent.com/1134236/90967302-d88d3d00-e4e5-11ea-9b65-68a2dbadf0d4.png)

**Comment by Velua** [comment]
up for testing.

**Comment by ashachaf** [comment]
isnt this the same as [insufficient balance when removing liquidity error #119](https://github.com/bancorprotocol/webapp/issues/119)

**Comment by Velua** [comment]
@ashachaf Sort of related, #119 is a clear indicator that we weren't handling the error correctly. This might be a side effect where we weren't updating the output amount anymore due to the method throwing however I cannot explain the error coming up other than it the fix might not have been in prod and still remaining in staging at the time.
