### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#1236]
There are a number of ways we can improve upon in performance, whether FPS or initial page load time, usually dictated by the API but not in all cases. 

Some ideas floated are 

# Reducing bundle size 
 Reduce the initial time it takes to download the app and will allow subsequent requests to fire earlier. 

# FPS optimisation
(Reduce choppiness), at the moment the app heavily relies on the use of Vue reactive getters which update the page on the fly based on several dependencies such as whitelisted pools, token meta data like images and pools as soon as any of these sources of data changes, however, this check runs frequently, including each time we do an API call, despite there being no changes, this will still run and can be CPU intensive enough to produce a drop in frames and produce the choppy feel of the app. Getters was a good idea when the app was smaller and had less data going into it, but now we're experiencing growing pains as we fetch more data from different sources each coming in at different times. 

We've previously looked at a few solutions,

## Vue ORM 
Allows data [normalisation](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape/) which ensures data need not be stored twice which results in diffing being more minimal thus better performance, however this would come at the cost of a large refactor nor does it seem like we'd see any Vue 3 support soon which means we'd have to delay any further Vue 3 update. 

## RX JS
We can utilise the ```combineLatest``` pattern we see in ```RxJS``` where we can detect incoming data and have more control over how the app reacts, we can also get rid of getters in favour of direct data sources which will improve FPS performance.

I vote we go down this path, as we'll get to further lean on RxJS which we're doing anyway and implementing this is quite minimal in terms of development time and risk.

**Comment by pingustar** [comment]
RxJS 4 president!

**Comment by Velua** [comment]
@Ran73Cohen thoughts?

**Comment by Ran73Cohen** [comment]
@Velua We can try and decrease initial load time by removing unused JS, however since we are using vue (any framework does the same) its not that simple since we have to reduce the size of our chunks that cant really edited or deleted.
[PageSpeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fapp.bancor.network%2Feth%2Fdata&tab=mobile) shows which chunks are responsible but it doesn't really help identifying which modules increase their size.
We should also look into reducing main thread work (maybe by reducing our reliance on vuex?) and separate the loading to more of a waterfall structure.

**Comment by ashachaf** [comment]
https://betterprogramming.pub/6-ways-to-speed-up-your-vue-js-application-2673a6f1cde4

**Comment by Ran73Cohen** [comment]
Stale
