### ISSUE TITLE
Pools that have no BNT/USDB in their reserves don't show up in the app

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#126]
Example -
https://etherscan.io/address/0x7ff10d4add8c9c2f5e47798cd60544ad91c1f4ec

**Comment by Velua** [comment]
This is expected behaviour as support for pools without network pools has not been implemented. 
How do you want to handle calculation of liquidity depth? Shall we proceed with calculation slippageless prices of all tokens from BNT and USDB pools then using those numbers to calculate liquidity depth for pools without a network token?

The value of USDB is hardcoded at $1 USD, technically this could be extended to further pegged tokens based on the USD but this might not be wise.

**Comment by StrateVic** [comment]
https://etherscan.io/address/0x7ff10d4add8c9c2f5e47798cd60544ad91c1f4ec

Please check this pool, its need to appear somewhere, i created it then disappear 

Thx
