### ISSUE TITLE
withdraw protected position error

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1357]
**Describe the bug**
trying to remove protected position.
remove BNT (50%) from my enjbnt pool position.

reproduce:
1. find a BNT protected position
2. try to withdraw it

![image](https://user-images.githubusercontent.com/40430285/115767223-8f152a80-a3b1-11eb-80a6-186e49c1ad6c.png)

**Comment by Velua** [comment]
Looks like this happened due to a breaking change on the contract at https://etherscan.io/tx/0x11434958a4802f1afcc1134f59cbbba6836df39389d00b0d4207cdf742f91825 

We were dependent on ```govToken()``` letting us know the vBNT address, which has now gone resulting in it being undefined. 

This is required during the remove protection process because we'll check to see if we need to approve the liquidity protection contract of the BNT amount on the vBNT token contract. 

I've since hard coded it, where else can we discover what the ```govToken``` is @yudilevi ?

**Comment by yudilevi** [comment]
There's no reliable way to get the network/gov tokens, I'd just hardcode them per chain.

**Comment by Velua** [comment]
Hardcoded
