### ISSUE TITLE
list of tokens on data page loading issues

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#155]
when visiting the data section, there is a short list of tokens that appear and after some time more tokens show up.
consider one of these options:
1. cache the token static data so you can display it before the blockchain data arrive
2. show the short list and include a loader animation at the bottom to indicate more data is loading
3. have a longer loading time (with loading animation) and display the page when all tokens data is available.

https://streamable.com/cskclt

**Comment by Velua** [comment]
We're planning to do 1 however this will be quite development heavy to implement, but when finished load times will be far quicker. 

The two part loading is by design, the initial load is to render the initial page quicker so the user has something rather than nothing. 

Will add a loading icon to indicate this.

**Comment by ashachaf** [comment]
duplicated task. closing.
