### ISSUE TITLE
WEB/BNT Pool not showing up

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#167]
copy paste from telegram, message from @yudilevi 

"and I don't see WEB which there is a pool for

WEB/BNT pool

and it's on katana -
https://katanapools.com/pool/view/WEBBNT"

**Comment by Velua** [comment]
@yudilevi 

I had hard coded 10 pools which we're set to be ignored due to mysterious behaviour with the eth-multicall, for some reason requests to these pools would fail so they would cause all the other pool requests to fail as well. 

WEB/BNT was part of this group of pools.

I've updated it so that initial 20 ish pools are loaded, then the remaining pools, then the mysterious ones.
