### ISSUE TITLE
data table - adding APR indication

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#392]
on the data page, we would like to add APR indication for protected pools only (same pools we indicate the protection shield for).

calculation - pool APR is the average position between token and bnt APR (as a pool, it shows the average considering both sides of the pool is staked)

APR data will show based on 1d ago.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=580%3A3392

**Comment by Velua** [comment]
- [ ] Create multi fetch support for whitelisted pools
- [ ] Shape for poolROI
- [ ] Decide on addition to ViewRelay or another getter.
- [ ] Define tooltip message

**Comment by Velua** [comment]
@ashachaf Figma suggests there's a tooltip, what is the message?

**Comment by Velua** [comment]
Current one day calculation is...
```

const poolToken = position.poolToken;
const reserveToken = position.reserveToken;
const reserveAmount = position.reserveAmount;
const poolRateN = new BigNumber(tknReserveBalance.weiAmount)
  .times(2)
  .toString();
const poolRateD = poolTokenSupply;

const reserveRateN = opposingTknBalance.weiAmount;
const reserveRateD = tknReserveBalance.weiAmount;

const poolRoi = await lpContract.methods
  .poolROI(
    poolToken,
    reserveToken,
    reserveAmount,
    poolRateN,
    poolRateD,
    reserveRateN,
    reserveRateD
  )

const magnitude = 365;

const calculatedAprDec = new BigNumber(poolRoi)
  .div(1000000)
  .minus(1)
  .times(magnitude);

```

Changing it so that above happens, but it's also repeated flipping the tknReserve balance and opposing reserve balance. 

Then returning the average of those two numbers.

**Comment by Velua** [comment]
TKN reserve balance in this instance is whatever the user depositing, opposing is whatever the other reserve is.

**Comment by yudilevi** [comment]
After looking at the different platforms in the space, we decided to go with a solution similar to what other platforms are doing.
Note that this is only relevant to the data page (unrelated to the protection page calculation).

- Show the fees over liquidity in the pool, meaning get all the conversion events from the last X blocks, get the fees off them and calculate their $ value - this has some performance implications in the current system so we'll need to do it in the background after the page loads. It also requires converting the fees to a single token representation in order to calculate the value efficiently.
- The column is currently not visible when you first load the page and only loads after we receive the data from the blockchain - it should always be visible and then be filled in with values in the background

This isn't generally an ideal solution - I can see why others in the market chose to use that value since it shows clean fees without impermanent loss. It doesn't actually show real gains for LPs but if we use a different value, it'll be harder for LPs to compare our pools with other pools in the market.

**Comment by Velua** [comment]
- 24 hour block span.
- ConversionEvent should list how much was paid in a fee. Terminating token is the one that is billed the fee. 
- Use existing conversion events, using the fees set on the pools.

**Comment by Velua** [comment]
This is now in place! Another issue was created for the volume work so closing this one.
