### ISSUE TITLE
Incorrect pool token amount

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#52]
when adding liquidity, you need to calculate the return of. pool tokeen amount.
currently, bnt pool token is worth ~1.02 bnt.
meaning,  if i add. 2 bnt, i should receive less than 2 pool tokens.

![image](https://user-images.githubusercontent.com/40430285/89646514-9b5d6400-d8c4-11ea-961f-bf0d3232008d.png)

**Comment by Velua** [comment]
Are you saying the rates should reflect the pool token return?

**Comment by Velua** [comment]
@pingustar knows what's up, added to the plate.

**Comment by pingustar** [comment]
@Velua 

Data is needed of calculation for expected return in Pool Tokens. Or have you that available already?

**Comment by Velua** [comment]
Waiting on me to provide ```expectedReturn``` for v2 pools add liquidity.

**Comment by Velua** [comment]
![Screenshot at 2020-08-14 08:11:50](https://user-images.githubusercontent.com/8017434/90192258-f5e74a80-de05-11ea-8abd-aa2a3ed813fc.png)

**Comment by Velua** [comment]
@ashachaf we haven't seen a mockup that displays this, is providing the pool token return for a deposit in line with the design/approach?

**Comment by Velua** [comment]
@pingustar double check and see if there's a mockup that reflects this in case I'm blind.

**Comment by pingustar** [comment]
@Velua @ashachaf 

for **V1** add liquidity we have this mockup: 
https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f17d104bacb0478b55d7138

currently we show the balances to be deposited instead of the pool token amount returned.
![image](https://user-images.githubusercontent.com/7262066/90383898-10792800-e081-11ea-857c-3ff7a8b946d8.png)

---

for **V2** add liquidity we have this mockup:
https://app.zeplin.io/project/5d70f6905eefcd18e1c40502/screen/5f17d1090847fb84fa1e127e

and currently we show the exact amount entered by the user as return, I believe it should be slightly less than that, not to sure what calculation that would be:
![image](https://user-images.githubusercontent.com/7262066/90384251-8f6e6080-e081-11ea-85d2-6adfc9b16489.png)

**Comment by ashachaf** [comment]
when adding liquidity, the summary page should indicate the amount of pool tokens received (not reserve tokens).
https://zpl.io/boqg4GE

also, the information we display in the gray box should be updated to fit the mockup.

**Comment by ashachaf** [comment]
phase out
