### ISSUE TITLE
24fee calculation based on existing data

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#522]
allow frontend. to. keep a list of when we change fee
use the correct fee percentage based on the event timestamp.

calculate the fee from every conversion event and sum the fee together to show 24h fees.

**Comment by Velua** [comment]
Some back story, 

Currently the implemented solution just loops over network conversion events and considers the **current** fee % set on pools as truth, however, in cases where the pool has changed fees in the past 24 hours these fees are considered in accurate. 

In #502 we implemented a bandaid solution where pool fees can be hardcoded with a blocknumber which gets us out of trouble for now. 

Our goal in this issue is to create a more long term solution where fees are calculated accurately. 

@H34D My current understanding is that we've decided to launch these requests immediately once pools are loaded in order to not increase wait times nor do we expect these requests to make any difference very often as they'll only introduce any change in cases where the pool fee has been set in the past 24 hours. 

Further discussion is continued in PR #526

**Comment by ashachaf** [comment]
seems this is not working on production.
we need to understand why.

**Comment by Velua** [comment]
While further work can be done to prioritise pools based on their liquidity depth I don't think that would still deliver a good experience as we'd like. 

From what I see the existing system works, just takes way too long to discover the pools we want given the concurrency limitation. 

Lets proceed with hard coding the fees till we can lean on the API.

**Comment by Velua** [comment]
Added sorting by a handful of hardcoded pools.
