### ISSUE TITLE
blank page on reload

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#53]
user complaints that at times,  the page refresh and the "widget" isnt loading.

![image](https://user-images.githubusercontent.com/40430285/89647333-170be080-d8c6-11ea-8d12-893cd9f5fa0d.png)

**Comment by Velua** [comment]
Cannot replicate.

**Comment by ashachaf** [comment]
go to pool
click add liquidity to bnt/ren v2 pool
select the ren token 
refresh the page
https://streamable.com/vfq92n

**Comment by pingustar** [comment]
@ashachaf thanks for the screencast, I am now able to reproduce it. It does not happen always it seams. I think it has to do with the way we load the data.

@Velua might this be due to the loading in chunks mechanism? Any idea how to resolve this? We might need to show another loading animation until the chunk with the correct pool information is loaded. 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/7262066/89903091-872ca600-dbe7-11ea-9c51-6771e14a8520.png">

**Comment by Velua** [comment]
Yeah this is likely a bug on the Vuex side, I'll look into it

**Comment by Velua** [comment]
Pushed to staging branch
