### ISSUE TITLE
previousPoolFees - add LINK

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#548]
```
 {
    oldDecFee: 0.01,
    blockNumber: ????,
    id: "0x04D0231162b4784b706908c787CE32bD075db9b7"
  }
```

@ashachaf do you know what the blockNumber is?

**Comment by yudilevi** [comment]
last change I see is from 6 days ago -
https://etherscan.io/tx/0xa4c51f03b32150d2f7cf4a431cfd753d12889794915532a3a27aa4fa29ffdcd8

**Comment by Velua** [comment]
I think the change is impending. @pingustar better to set it to the block number now. Then we'll update it again when we know the exact block number. 

Otherwise it will be changed and still take us 15 minutes ish to respond. In that time there's a more inaccurate representation than what we'd have if we just set it to the current block and adjust it when we know the exact block.

**Comment by ashachaf** [comment]
please use this block:
11268926

this is a place holder. once the transaction is done, a new block number will be shared.

**Comment by pingustar** [comment]
@ashachaf changes are pushed to staging in commit https://github.com/bancorprotocol/webapp/pull/549/commits/22ad1ef3d0d8d2e040fd80ba3af4c5c1bb269186

**Comment by Velua** [comment]
Awesome stuff @pingustar 
- [ ] Move this change to prod.
- [ ] Set the exact block upon @ashachaf 's feedback.

**Comment by pingustar** [comment]
changes are deploying to production now.

**Comment by Velua** [comment]
Closing now given it doesn't matter if the exact block is in there or not by now.
