### ISSUE TITLE
Transaction confirmation popup - show etherscan link right away

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#585]
Currently, when the user submits a transaction, we show a popup that's waiting for the tx confirmation, and only after the tx is confirmed, we show a "transaction confirmed" message with the link to etherscan.
A better approach is to show a "transaction submitted" popup and immediately show the etherscan URL and allow the user to track it there.

**Comment by sirius651** [comment]
@yudilevi  https://github.com/bancorprotocol/webapp/pull/624#issuecomment-737094770  we concern with this out of sync issue, any thoughts?

**Comment by yudilevi** [comment]
@sirius651 I don't see how these issues are related - the UI should show the tx hash immediately and in the background monitor the tx, query the balance periodically or get events for balance updates.

**Comment by Velua** [comment]
He's pointing out that our balances checks won't be accurate until there's a block confirmation, so in the mean time there's a small amount of time where the user can see their old balance until a block confirmation happens. Shall we accept this new behaviour?

**Comment by yudilevi** [comment]
Yup, of course - that's how the underlying platform works so it's acceptable.

**Comment by yudilevi** [comment]
The popup is still waiting for 1 block instead of showing the tx hash immediately.

**Comment by Velua** [comment]
What kind of transaction do you see this on?

**Comment by yudilevi** [comment]
The actual swap (not approve).

**Comment by Velua** [comment]
@sirius651 it appears ```resolveImmediately``` isn't set on the convert transaction.

Can you also ensure that balance checks are getting triggered after a block confirmation and not getting fired before, it looks like we're open to this. 

I've created this [PR](https://github.com/bancorprotocol/webapp/pull/816) , please go through the code and utilise the ```onConfirmation``` call back in any cases where we are calling ```this.spamBalances``` or expecting any changes after a block confirmation so that we can get away with this move of immediately resolving.
