### ISSUE TITLE
add liquidity "space available" not showing

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#586]
it seems that when the page is open for some time with no refresh, there is an error which cause "space available" not to be calculated.

open data->add liquidity 
keep open for several minutes

![image](https://user-images.githubusercontent.com/40430285/99902567-62a49780-2cc7-11eb-9584-9ef3e42944c2.png)

**Comment by pingustar** [comment]
@ashachaf is this still happening? After about 10 minutes I can still see the values.

**Comment by ashachaf** [comment]
1. i still see this issue on browsers that are open for some time without refresh (after refresh this works)
2. when the "available space" is smaller than the input amount, we should not allow user to proceed.

![image](https://user-images.githubusercontent.com/40430285/100089890-12f6d500-2e5b-11eb-9f8b-60617b57f339.png)
![image](https://user-images.githubusercontent.com/40430285/100089927-1d18d380-2e5b-11eb-8bde-9ba8112eb691.png)
![image](https://user-images.githubusercontent.com/40430285/100089946-24d87800-2e5b-11eb-819e-435e14d88c94.png)
![image](https://user-images.githubusercontent.com/40430285/100089963-2ace5900-2e5b-11eb-8693-84bafa4d96ec.png)
after refresh, it works
![image](https://user-images.githubusercontent.com/40430285/100090191-77b22f80-2e5b-11eb-8d67-d94d7e227103.png)

**Comment by pingustar** [comment]
1. after what time (estimate is fine) do you see this happening? I am going close to 1 hour now and cannot reproduce.
2. this seems to be happening due to issue 1. - very likely that 2. will be resolved once we resolve 1.

@ashachaf does this need to be tagged priority? I don't think this effects a lot of people.

Another concern with this is, that if we have the browser window open for hours, the "available space" data might be outdated and not accurate anymore.

Refreshing in the background might blow the rate limits, depending how often we refresh. Not sure what the best way is to resolve this. 

@Velua @H34D any thoughts about how to tackle this?

**Comment by pingustar** [comment]
ok, I was able to get this error reproduced.

I had the browser window open for about 2h and then navigated away from the "Add Liquidity Protection" screen and navigate back to it.

**Comment by pingustar** [comment]
@ashachaf I have added an interval to fetch the data. This should resolve the data disappearing and will keep the data up to date if you have the window open over a longer period of time.

It is on staging for testing.

**Comment by pingustar** [comment]
@ashachaf I assume this is resolved. If you still have trouble with this, please reopen.

**Comment by pingustar** [comment]
happened again today.

**Comment by sirius651** [comment]
After tested out, It doesn't seem to reproduced in my side. Do you know how to reproduce this in detail? @pingustar

**Comment by pingustar** [comment]
I had the browser window open for about 2h and then navigated away from the "Add Liquidity Protection" screen and navigate back to it.
