### ISSUE TITLE
data and protection tables do not load

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#616]
i dont get any special errors on console.
i dont have rate limit on alchemy.
![image](https://user-images.githubusercontent.com/40430285/100538652-b8ce8900-3239-11eb-8c40-456f15592339.png)

![image](https://user-images.githubusercontent.com/40430285/100538657-bff59700-3239-11eb-8785-ed23a6512dbd.png)

data table sometimes loads with partial data
![image](https://user-images.githubusercontent.com/40430285/100538674-d996de80-3239-11eb-87ab-52ae443d75d1.png)
when clicking the + to stake it opens a blank page.
![image](https://user-images.githubusercontent.com/40430285/100538682-ec111800-3239-11eb-8bf1-687f1608bb4d.png)

try to go back to the data page, all data is gone again.

**Comment by pingustar** [comment]
hotfix to master branch deployed. App seems functional again with the exception of the pool data table. 

The Pool Data Table currently does not show:
- Volume
- Fees
- APR

For reference, my hotfix commits:

- https://github.com/bancorprotocol/webapp/commit/b1eace5571bc82e8ba828f7664238b54a03d9c3b
- https://github.com/bancorprotocol/webapp/commit/95b3cbcc8c4c3517e6124c3a8479a8b407891f20
- https://github.com/bancorprotocol/webapp/commit/d9cb460769ac6257f8539d93559afb9ff856fabb

**Comment by Velua** [comment]
I've simply reverted @pingustar 's changes to the original state and the app appears functional. 
Also changed fee calculation to pass with little or no fees calculated rather than failing entirely. 

We should probably map out where requests can go wrong or fail and what to do in those events. Should the Alchemy endpoint for events fail but everything else works OK should the app crash? Or try x, y, z then render an error on the screen and hide fee related dependencies.
