### ISSUE TITLE
Remove 100% of my Liquidity throws insufficient funds error

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#640]
**To Reproduce**
1. Remove pool tokens from v1 pool
2. Click balance to select max 
3. calculation is made for opposite side
4. error shown: insufficient funds

**Expected behavior**
calculation should return max balance for opposing side

**Screenshots**
![image](https://user-images.githubusercontent.com/7262066/100848658-b78f9d00-3481-11eb-80b7-403bc8acdf4d.png)

**Comment by Velua** [comment]
Whomever picks up 
- [ ] Ensure balance insufficient balance error is raised by BigNumber and not doing a native JS math operators >.

Could either silence the balance error should the ```calculateOpposingXXX``` error be the one changing it, otherwise see the root issue in the calculation and why it's suggesting one can remove more liquidity than they can. 

@pingustar do you remember that other issue that was raised to change this in general? Because this style wasn't inline with what Yudi wanted that time, I think he wanted it pool token orientated instead, in which case this becomes more simple anyway.

**Comment by pingustar** [comment]
not to sure what that other issue was about, but I remember that there was a overhaul planned for this screen.

**Comment by H34D** [comment]
this is definitely related to #560

**Comment by pingustar** [comment]
@Ran73Cohen this can be a good challenge, tricky one. Lets see if you can get to the bottom of this. Feel free to ask for help.
