### ISSUE TITLE
Update the app to support the new network token minting limits system

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#669]
This change also involves a design change in the contracts - the protection contract was broken into 2 different contracts due to binary size restrictions -
- LiquidityProtection - holds the logic only
- LiquidityProtectionSettings - holds all the protection settings, **including the whitelist** etc. Can be accessed by querying the protection contract.

Note: high tier pools aren't defined in the new contracts anymore and will be re-introduced into the system when the staking rewards contracts are deployed (requires hardcoding for now).

Limit changes -
The ratio was removed and replaced by a custom limit per pool (`settings.networkTokenMintingLimits`) and a default if no custom limit is defined (`settings.defaultNetworkTokenMintingLimit`).
A minimum liquidity was introduced - the protocol will only mint tokens for pools have more network token liquidity than the minimum defined (`settings.minNetworkTokenLiquidityForMinting`).
In addition, the protocol now tracks how much was minted per pool (`settings.networkTokensMinted`).

Network token limit calculation becomes very simple -
`limit = settings.networkTokenMintingLimits(pool address).`
if the limit above is undefined, the default limit is used instead.
The current amount the protocol can mint is `limit - settings.networkTokensMinted(pool address)`.

Ropsten deployment is updated with the changes.

**Comment by ashachaf** [comment]
replacing task #621 
@H34D

**Comment by H34D** [comment]
@ashachaf any test data on ropsten? networkTokenMintingLimits returns 0 always on ropsten. Also i believe that networkTokenMintingLimits cannot be "undefined" but rather 0 if not set because of the defaults of uint256.

**Comment by ashachaf** [comment]
Xxxbnt

New settings contract, pull the pool limit.
https://ropsten.etherscan.io/address/0xff3ddf48b6ba7773e19b635b3bf0d339525a71cf#readContract
networkTokenMintingLimit: 0x6dc51c45f409385fc99a1c7b316d7fab15d66474
Pool minting: 50000000000000000000000

Now also identify how many bnt were minted already.
networkTokensMinting: 0x6dc51c45f409385fc99a1c7b316d7fab15d66474
26554714837518616832230

On the pool converter contract, check the reserve balance to identify the pool spot rate.
https://ropsten.etherscan.io/address/0xe289d3bdcfd3a9c6d08428c8bf213988370eb738#readContract
Reserves, reserveBalance, connectors, connectorBalance, all return this value.
BNT: 0xf35ccfbce1228014f66809edafcdb836bfe388f5: 27688994896013371337745
XXX: 0x34748f3e5cddbbb7c2a7bec888fef3873a462de7: 16725525059808512049638

Since the amount is in bnt, you need to identify the rate of 1bnt in tkn units.
1 bnt rate = tkn reserve balance / bnt reserve balance
1 bnt rate = 16725525059808512049638/27688994896013371337745 = 0.60404955552 tkn

Now that we have the needed information, we can calculate the space available:
We can calculate the amount of bnt that we can still mint.
limits:
Available minting limit = networkTokenMintingLimit - networkTokensMinting
Available minting limit = 50000000000000000000000 - 26554714837518616832230 = 23445285162481383167770 bnt

And calculate what to show on the space available indication for each side.
Bnt side, as bnt can be staked against minted bnt in the pool, we take the value as is.
BNT space available = networkTokensMinting = 26554714837518616832230

Tkn side requires calculation.
TKN space available = Available minting limit * 1 bnt rate = 23445285162481383167770 * 0.60404955552 =  14162114081436530482766.2780895904 tkn
In order to prevent transactions to fail when price shifts between the moment you send the transaction and the moment it gets executed, I would apply 0.5% buffer. Meaning, display space available = (TKN space available * 99.5%) = 14162114081436530482766.2780895904 * 99.5% = 14091303511029347830352.446699142448
(Remember to trim the decimal in this number as we work with Wei. And multiply this with the tkn decimals)

**Comment by ashachaf** [comment]
### protected position cliff and vesting:
moved to new settings contract: https://ropsten.etherscan.io/address/0xff3ddf48b6ba7773e19b635b3bf0d339525a71cf#readContract

maxProtectionDelay = total vesting duration for "full coverage"
minProtectionDelay = cliff duration

**Comment by H34D** [comment]
> ### protected position cliff and vesting:
> moved to new settings contract: https://ropsten.etherscan.io/address/0xff3ddf48b6ba7773e19b635b3bf0d339525a71cf#readContract
> 
> maxProtectionDelay = total vesting duration for "full coverage"
> minProtectionDelay = cliff duration

please open another issue for this one

**Comment by ashachaf** [comment]
bnt space available calculation is incorrect.
please make sure you indicate the bnt amount that was minted so far, this represents that space available for bnt.
ethtbnt converter: 0xc83241BFcfE9A2CDe5B98EdC009420A6dc5Ed241
ethtbnt token: 0x1aCE5DD13Ba14CA42695A905526f2ec366720b13
checking function networkTokensMinted, the result is 54.92809205995676547 BNT.
which means that the space available for single side BNT staking is 54.92809205995676547 BNT and not 9945.

![image](https://user-images.githubusercontent.com/40430285/102006611-fc8dbc00-3d2a-11eb-9bc7-fec931fd3f3a.png)

**Comment by ashachaf** [comment]
seems 0.5% is too high of a buffer.
we can lower it to 0.1%.
related to this:
> In order to prevent transactions to fail when price shifts between the moment you send the transaction and the moment it gets executed, I would apply 0.5% buffer. Meaning, display space available = (TKN space available * 99.5%) = 14162114081436530482766.2780895904 * 99.5% = 14091303511029347830352.446699142448

**Comment by H34D** [comment]
> bnt space available calculation is incorrect.
> please make sure you indicate the bnt amount that was minted so far, this represents that space available for bnt.
> ethtbnt converter: 0xc83241BFcfE9A2CDe5B98EdC009420A6dc5Ed241
> ethtbnt token: 0x1aCE5DD13Ba14CA42695A905526f2ec366720b13
> checking function networkTokensMinted, the result is 54.92809205995676547 BNT.
> which means that the space available for single side BNT staking is 54.92809205995676547 BNT and not 9945.

cool, will change that. thanks

**Comment by H34D** [comment]
done
