### ISSUE TITLE
Claim rewards

### ISSUE THREAD

**Issue by H34D** [bancorprotocol/webapp#676]
**Is your feature request related to a problem? Please describe.**
Provide a process where users can register their positions to receive rewards, see their available rewards, withdraw and restake.

**Background**
Some bancor liquidity pools have rewards allocated for users who stake liquidity in them. To qualify for these rewards, you need to have a protected position activite on the relevant pool that receives rewards.
UPDATE - we will calculate the rewards off-chain, which means the LM contract will include all eligible wallets and positions with no need to “register” or take action from the user’s side. 
Meaning, if you have a protected position and it is on a pool that qualifies for LM rewards, that pool id will be available on the LM  contract and you can immediately interact (claim/restake) with it.

**Describe the solution you'd like**
see google docs for details

**Attached Issues**
- [ ] Fetch Rewards information from the Rewards contract instead of hard coding it in the frontend #809
- [ ] Implement Claiming of Rewards #810

**Comment by ashachaf** [comment]
# protection table
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A22

## summary table
the new summary table will include data and actions:
### Data:
1. claimable rewards: this value indicates the currently available rewards that were already signed on the onchain contract and are claimable.
- this value is pulled from the contract on-chain. it is updated every few days at first, so best if you track events and update when needed (instead of trying to pull it all the time when it doesnt change)
- calculate the value in USD based on the BNT price to USD in the system
- tool tip: Current rewards that are available to restake in pools and earn fees and rewards when available
2. future rewards: this value indicates the rewards that are calculated off-chain and represents the rewards that WILL BE CLAIMABLE once the onchain contract is updated. this value keeps growing until it update the on-chain contract and then it starts at 0 again.
- pull this data from an off-chain api
- refresh often as this is a growing number that increase every second (off-chain calculate it by seconds, not blocks)
- calculate the value in USD based on the BNT price to USD in the system
- tool tip: Rewards that will be available and added to claimable rewards in the next update
3. total rewards to date: this value indicates the total rewards given to the user. 
- pull this data from an off-chain api
- refresh often as this is a growing number that increase every second (off-chain calculate it by seconds, not blocks)
- calculate the value in USD based on the BNT price to USD in the system
- tool tip: Total rewards received 

**data movement**
in order to show movement, we would like to use some type of increasing number effect.
- on refresh/load: start all 3 values at 0 and grow them to the number they should be over a span of 3 seconds.
- future and total rewards: if refresh of the data is every 15 seconds, break the delta increase to show over a span of 15 seconds. 
- claimable rewards: 1) when user claims rewards, count down to 0 in a span of 3 seconds. 2) when there is an update to the claimable rewards, increase the number over a span of 30 seconds 
- code sample to the effect: https://codepen.io/duvander/pen/KXOpXw

### Actions:
1. withdraw: this action is less preferred and we would like the user to "avoid" it as it will reset the multiplier.
- https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A643
2. restake: this is the main action we would like users to use with their rewards.
- clicking the "restake" will open the pool selection interface: https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A967
- once you select a pool, you will arrive at this interface: https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A813

## protection table new column/s
in order to make space in the table which is getting too big to display, we have done few changes to the table columns.
1. fees & ROI: merging these two columns into 1 will save space and merge two similar items together.
- tool tip: Fees your stake has earned since you entered the pool and the Return on Investment given full protection.
2. rewards: indication of "lifetime rewards" 
- per row (in case of group, sum of all rows)
- position multiplier (coming from off-chain api and changes every 7 days). group row should average this number. example: (row 1 multiplier + row 2 multiplier +...+ row N multiplier) / N rows
3. actions: changing to icons
- mouse over: 1) group icon: "Un-Group" / "Close Group" 2) "Withdraw"


https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A22

**Comment by Velua** [comment]
Comment from @ashachaf 

make sure the update goes live together.

check: 
IF the user has protected positions in pools that receive rewards, show the new warning.

https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=1443%3A1158

**Comment by pingustar** [comment]
@ashachaf as a followup to our call today:

Currently we need further information for:

**UI mockups and contracts not aligned** 
- Withdraw rewards
- ReStake rewards

**Where to get this data**
-  Future Rewards 
- Total Reward to date 
- Multiplier

**Comment by ashachaf** [comment]
@pingustar @Velua @H34D 
please review the task details and provide feedback.

**Comment by Velua** [comment]
> return the claimable rewards in bnt amount (Wei) for the indicated wallet.

What's an indicated wallet? @ashachaf

**Comment by ashachaf** [comment]
> > return the claimable rewards in bnt amount (Wei) for the indicated wallet.
> 
> What's an indicated wallet? @ashachaf

the connected wallet you are checking the data for.

**Comment by Velua** [comment]
Let's put this on pause now, awaiting further information from @ashachaf

**Comment by ashachaf** [comment]
@Velua @pingustar @H34D 
lets discuss.
https://docs.google.com/document/d/1KOVa-73JEdCvE6LhSWBnIbrF0ezfeaUQBtd2HdRcAe8/edit#

**Comment by Velua** [comment]
Permission requested from my eosi*****@gmail.com account

**Comment by pingustar** [comment]
**Current Status Update:**

- `claimRewards` branch is deployed to staging **manually**. I didnt want to merge it into staging branch yet.
- rewards is getting close and I can finish the rest tomorrow
- **Claim Rewards Features are NOT tested yet**
- the api has been updated and broke the frontend at multiple fronts. I believe something with decimal/precision got changed.

**To Do:**
- @Velua review `stakeRewards` and `claimRewards` in `store/rewards/index.ts`
- @Velua fix errors based on api changes. @ashachaf and Yarif have more information
- get `claimRewards` branch in production ready state
- test claim reward features -> currently unclear how

**Comment by ashachaf** [comment]
@pingustar 
#### bug:
"withdraw" text doesnt show up on dark mode
![image](https://user-images.githubusercontent.com/40430285/105964969-8f8c7680-608b-11eb-9024-0d393ecd6454.png)

#### bug:
Rewards amount and "BNT" jump left to right with the numbers. please try to set them in fix positions so they do not move.
https://streamable.com/w7xfel

#### text change:
please update the main protection page:
**current:**
You can protect your token pools with our special insurance for impermanent loss by simply adding insurance to each of your transactions.
**updated:**
Manage your protected positions in Bancor pools and track and analyze your returns.

**Comment by pingustar** [comment]
text and button is fixed.
