### ISSUE TITLE
Review RemainingTime2.vue component

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#733]
There appears to be both ```RemainingTime.vue``` and ```RemainingTime2.vue``` components, 
Determine what the difference is, shouldn't be warranted to have two unless for a good reason. See if we can get whatever accommodations there may be in the second component from a prop in the first one instead.

**Comment by Velua** [comment]
@pingustar Taking a peek at commit history you might have some knowledge of this.

**Comment by pingustar** [comment]
`RemainingTime.vue` was build for the vote page and has a bunch of specific logic and css for that usecase. Due to time pressure I replicated a simpler version of it for the protected positions table.

Given the latest changes in regards of mockups. It looks like we are going back to a simpler progress bar and `RemainingTime2.vue` will no longer be in use.

![image](https://user-images.githubusercontent.com/7262066/102325634-a8314900-3f83-11eb-8d64-9160fba39194.png)

**Comment by Velua** [comment]
Awesome lets just kill it then. 

- [ ] Delete ```RemainingTime2.vue```

**Comment by Velua** [comment]
@Ran73Cohen we want to decommision ```RemainingTime2.vue``` and get away with it's forked component ```RemainingTime.vue``` instead, currently ```RemainingTime2.vue``` is used by ```ProtectedTable.vue```

See if you can replace it with ```RemainingTime.vue``` instead, use props to make it more reusable if you need too. Too much code duplication to warrant a 2nd component long term.

**Comment by pingustar** [comment]
The `RemainingTime2.vue` will not be needed anymore once I get around to update the protected table to fully match the mockups.

**Comment by Velua** [comment]
Okay so this is best kept under your wing?
