### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by Ran73Cohen** [bancorprotocol/webapp#815]
Related to #297
I added support for i18n in [i18n_support branch](https://github.com/bancorprotocol/webapp/tree/feature/i18n_support)
Whats left to do?

- [x] Create the base english file with all the keys and sentences and reference it across the code

- [ ] Decide on the UI for switching between locales

After that we can simply copy the en.ts file to any other language and translate the sentences (without touching the keys)
Import to i18n.ts file and add the language to `getLanguegeByLocale ` method in the same file

Referencing in the component is done like so:
` <p> {{ $t('YOUR_KEY') }} </p>`

In scripts you need to import i18n (under src)

```
import { i18n } from "../../i18n/i18n";
i18n.t("YOUR_KEY")
```

**Comment by Velua** [comment]
Could have just jumped on the original issue of #297 instead of creating another, be sure to assign yourself to this as well if you're working on it. 

See if you can import via ```import { i18n } from "@/whatever/i18n/i18n";``` instead of relative pathing. 

Create a PR of your branch against staging and mark as a draft if you're not finished yet, makes it nice and obvious what a branch is doing. You can then link this issue against the PR.
