### ISSUE TITLE
Support the new "disable add liquidity" setting

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#962]
It's now possible to disable single token staking with a specific reserve.
So for example, for a given pool, the community can decide that it's only possible to provide liquidity with TKN while the protocol is the only one that provides BNT liquidity.

For that, we introduced a new flag in the settings contract -
https://docs.bancor.network/ethereum-contracts/ethereum-api-reference/liquidity-protection/liquidityprotectionsettings#LiquidityProtectionSettings-addLiquidityDisabled-contract-IConverterAnchor-contract-IERC20Token-

If the flag is set for a specific reserve, it shouldn't be visible in the "Add Liquidity" popup.

**Comment by Velua** [comment]
Can we safely assume that TKN would never be disabled? Or should we fire this requests twice to cover both reserves to check?

**Comment by Velua** [comment]
Pretty much ready for this now, let me know when this new method is deployed to a contract to test out. @yudilevi

**Comment by ashachaf** [comment]
https://www.figma.com/file/3yED7o7TgoLwoEjV2EkRLL/Bancor-V2?node-id=2357%3A0

we would like to handle this on the "stake and protect" screen.
when a user select a pool+token combination, we should show the popup with the following:
1. disable the input field
2. update the error message to indicate this pool does not support single token staking with the selected reserve. 
text: The selected pool supports adding liquidity using {TKN} only. In order to add liquidity, please select the 2nd reserve.
3. "stake" call to action should stay disabled

**Comment by Velua** [comment]
Awesome, a new update is building now which fulfils this request. 

In order to mock it in this branch, I've hard coded all pools to only accept TKN.

**Comment by yudilevi** [comment]
It's already deployed both on ropsten and on mainnet. TKN can also be disabled in some cases.

**Comment by Velua** [comment]
Any known pools on ropsten or mainnet that have a reserve disabled?
